"""MemBank initialization service — M-023 MemBankInitializationService.

Safe check, plan and apply for AgentMemBank Directory Contract initialization
over an existing Obsidian Vault.
"""

from __future__ import annotations

import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from memory_mcp.observability import (
    log_trace_anchor,
    new_trace_id,
)
from memory_mcp.process_event_log import ProcessEvent, record_process_event
from memory_mcp.vault_fs import write_file_atomic
from memory_mcp.vault_layout import (
    DirectoryContract,
    detect_directory_drift,
    detect_vault_layout,
)

if TYPE_CHECKING:
    from memory_mcp.config import ServerConfig

MODULE = "membank_init_service"
MODULE_BLOCK = "M-023"

PROJECTION_FILE = "AgentMemBank.md"


def _record_init_event(
    event_type: str,
    severity: str,
    agent_id: str,
    trace_id: str,
    mode: str,
    message: str = "",
    error_code: str = "",
    config: ServerConfig | None = None,
) -> None:
    if config is None:
        return
    db_path = config.process_event_db_path or ""
    if not db_path:
        return
    event = ProcessEvent(
        event_type=event_type,
        category="membank_init",
        severity=severity,
        agent_id=agent_id,
        trace_id=trace_id,
        message=message,
        error_code=error_code,
    )
    try:
        record_process_event(db_path, event)
    except Exception:
        pass


@dataclass
class InitAction:
    type: str
    path: str
    status: str


@dataclass
class MemBankInitPlan:
    actions: list[InitAction] = field(default_factory=list)
    missing_directories: list[str] = field(default_factory=list)
    projection_needed: bool = False
    is_idempotent: bool = False
    directory_contract: DirectoryContract | None = None


@dataclass
class MemBankInitResult:
    success: bool
    actions_taken: list[InitAction] = field(default_factory=list)
    audit_event_id: str | None = None
    message: str = ""
    trace_id: str = ""


def _list_actual_dirs(vault_root: str) -> list[str]:
    try:
        return sorted(
            d for d in os.listdir(vault_root)
            if os.path.isdir(os.path.join(vault_root, d))
        )
    except OSError:
        return []


def _build_projection_content(directory_contract: DirectoryContract) -> str:
    lines = ["# Agent MemBank Directory", ""]
    for key in sorted(directory_contract.keys):
        cp = directory_contract.keys[key]
        lines.append(f"- `{cp.relative_path}` — {key}")
    lines.append("")
    lines.append("*Generated by AgentMemBank MCP Server — M-023 MemBankInitializationService*")
    lines.append("")
    return "\n".join(lines)


def create_init_plan(
    vault_root: str,
    directory_contract: DirectoryContract,
) -> MemBankInitPlan:
    trace_id = new_trace_id()

    actions: list[InitAction] = []
    missing_directories: list[str] = []

    for key in sorted(directory_contract.keys):
        cp = directory_contract.keys[key]
        if not os.path.isdir(cp.absolute_path):
            actions.append(InitAction(type="CREATE_DIR", path=cp.absolute_path, status="pending"))
            missing_directories.append(key)
        else:
            actions.append(InitAction(type="SKIP_EXISTS", path=cp.absolute_path, status="exists"))

    projection_path = os.path.join(vault_root, PROJECTION_FILE)
    projection_needed = not os.path.isfile(projection_path)

    is_idempotent = len(missing_directories) == 0 and not projection_needed

    log_trace_anchor(
        level="INFO",
        event="membank_init.plan.created",
        trace_id=trace_id,
        module=MODULE,
        function="create_init_plan",
        block=MODULE_BLOCK,
        data={
            "missing_directories": missing_directories,
            "projection_needed": projection_needed,
            "total_actions": len(actions),
            "is_idempotent": is_idempotent,
        },
    )

    return MemBankInitPlan(
        actions=actions,
        missing_directories=missing_directories,
        projection_needed=projection_needed,
        is_idempotent=is_idempotent,
        directory_contract=directory_contract,
    )


async def apply_init_plan(
    plan: MemBankInitPlan,
    vault_root: str,
    agent_id: str,
    trace_id: str,
    config: ServerConfig | None = None,
    profile: str = "",
) -> MemBankInitResult:
    log_trace_anchor(
        level="INFO",
        event="membank_init.apply.started",
        trace_id=trace_id,
        module=MODULE,
        function="apply_init_plan",
        block=MODULE_BLOCK,
        data={
            "vault_root": vault_root,
            "missing_directories": plan.missing_directories,
            "projection_needed": plan.projection_needed,
        },
    )

    if profile == "readonly_agent":
        log_trace_anchor(
            level="WARNING",
            event="membank_init.apply.denied",
            trace_id=trace_id,
            module=MODULE,
            function="apply_init_plan",
            block=MODULE_BLOCK,
            data={"reason": "readonly_agent profile cannot initialize vault"},
        )
        return MemBankInitResult(
            success=False,
            message="Profile 'readonly_agent' cannot initialize vault",
            trace_id=trace_id,
        )

    if config is not None:
        from memory_mcp.policy import check_path_policy

        for action in plan.actions:
            if action.type == "CREATE_DIR":
                decision = check_path_policy(action.path, config)
                if not decision.allowed:
                    log_trace_anchor(
                        level="WARNING",
                        event="membank_init.apply.denied",
                        trace_id=trace_id,
                        module=MODULE,
                        function="apply_init_plan",
                        block=MODULE_BLOCK,
                        data={"path": action.path, "reason": decision.reason},
                    )
                    return MemBankInitResult(
                        success=False,
                        message=f"Path denied by policy: {action.path} — {decision.reason}",
                        trace_id=trace_id,
                    )

    actions_taken: list[InitAction] = []

    for action in plan.actions:
        if action.type == "CREATE_DIR":
            os.makedirs(action.path, exist_ok=True)
            action.status = "completed"
            actions_taken.append(action)
        elif action.type == "SKIP_EXISTS":
            actions_taken.append(action)

    if plan.projection_needed:
        dc = plan.directory_contract
        projection_content = _build_projection_content(dc) if dc else "# Agent MemBank Directory\n\n*Generated by AgentMemBank MCP Server — M-023*\n"
        write_file_atomic(vault_root, PROJECTION_FILE, projection_content)
        proj_action = InitAction(
            type="CREATE_PROJECTION",
            path=os.path.join(vault_root, PROJECTION_FILE),
            status="completed",
        )
        actions_taken.append(proj_action)

    audit_event_id: str | None = None
    if config is not None:
        affected_paths = [a.path for a in actions_taken if a.status == "completed"]
        event_data = {
            "event_id": str(uuid.uuid4()),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent_id": agent_id,
            "operation": "init",
            "path": vault_root,
            "old_revision": "",
            "new_revision": "",
            "dry_run": False,
            "policy_profile": profile or "unknown",
            "result": "success",
            "affected_paths": affected_paths,
            "trace_id": trace_id,
        }
        from memory_mcp.audit_log import record_event

        event = await record_event(event_data, config)
        audit_event_id = event.event_id

    log_trace_anchor(
        level="INFO",
        event="membank_init.apply.completed",
        trace_id=trace_id,
        module=MODULE,
        function="apply_init_plan",
        block=MODULE_BLOCK,
        data={
            "actions_taken_count": len([a for a in actions_taken if a.status == "completed"]),
            "audit_event_id": audit_event_id,
        },
    )

    return MemBankInitResult(
        success=True,
        actions_taken=actions_taken,
        audit_event_id=audit_event_id,
        message="Vault initialization completed successfully",
        trace_id=trace_id,
    )


async def membank_init(
    vault_root: str,
    mode: str,
    agent_id: str,
    trace_id: str,
    directory_contract: DirectoryContract,
    profile: str,
    config: ServerConfig | None = None,
) -> MemBankInitResult:
    valid_modes = {"check_only", "dry_run", "apply"}
    if mode not in valid_modes:
        _record_init_event("membank_init.invalid_mode", "ERROR", agent_id, trace_id, mode,
                           message=f"Unknown mode: {mode}", config=config)
        return MemBankInitResult(
            success=False,
            message=f"Unknown mode '{mode}'. Valid modes: {', '.join(sorted(valid_modes))}",
            trace_id=trace_id,
        )

    _record_init_event("membank_init.started", "INFO", agent_id, trace_id, mode,
                       message=f"Mode: {mode}", config=config)

    if mode == "check_only":
        layout_report = None
        try:
            layout_report = detect_vault_layout(vault_root, require_obsidian_marker=True)
        except Exception:
            pass

        actual_dirs = _list_actual_dirs(vault_root)
        drift_report = detect_directory_drift(directory_contract, vault_root, actual_dirs)

        obsidian_ok = layout_report is not None and layout_report.obsidian_marker_found
        vault_healthy = drift_report.ok and obsidian_ok

        return MemBankInitResult(
            success=vault_healthy,
            message=(
                f"Check-only report: obsidian_marker={obsidian_ok}, "
                f"missing_canonical={drift_report.missing_canonical}, "
                f"ambiguous_aliases={drift_report.ambiguous_aliases}, "
                f"unknown_dirs={drift_report.unknown_dirs}"
            ),
            trace_id=trace_id,
        )

    if mode == "dry_run":
        plan = create_init_plan(vault_root, directory_contract)
        _record_init_event("membank_init.plan_created", "INFO", agent_id, trace_id, mode,
                           message=f"Dry-run: {len(plan.missing_directories)} missing dirs", config=config)
        return MemBankInitResult(
            success=True,
            message=(
                f"Dry-run plan: {len(plan.missing_directories)} missing directories "
                f"({plan.missing_directories}), projection_needed={plan.projection_needed}"
            ),
            actions_taken=plan.actions,
            trace_id=trace_id,
        )

    if mode == "apply":
        if profile == "readonly_agent":
            log_trace_anchor(
                level="WARNING",
                event="membank_init.apply.denied",
                trace_id=trace_id,
                module=MODULE,
                function="membank_init",
                block=MODULE_BLOCK,
                data={"reason": "readonly_agent profile cannot initialize vault"},
            )
            return MemBankInitResult(
                success=False,
                message="Profile 'readonly_agent' cannot initialize vault",
                trace_id=trace_id,
            )

        try:
            detect_vault_layout(vault_root, require_obsidian_marker=True)
        except Exception as exc:
            return MemBankInitResult(
                success=False,
                message=f"Vault layout detection failed: {exc}",
                trace_id=trace_id,
            )

        actual_dirs = _list_actual_dirs(vault_root)
        drift_report = detect_directory_drift(directory_contract, vault_root, actual_dirs)

        if drift_report.unknown_dirs:
            log_trace_anchor(
                level="WARNING",
                event="membank_init.drift_blocked",
                trace_id=trace_id,
                module=MODULE,
                function="membank_init",
                block=MODULE_BLOCK,
                data={
                    "ambiguous_aliases": drift_report.ambiguous_aliases,
                    "unknown_dirs": drift_report.unknown_dirs,
                },
            )
            return MemBankInitResult(
                success=False,
                message=(
                    f"Ambiguous drift blocks apply: "
                    f"ambiguous_aliases={drift_report.ambiguous_aliases}, "
                    f"unknown_dirs={drift_report.unknown_dirs}"
                ),
                trace_id=trace_id,
            )

        plan = create_init_plan(vault_root, directory_contract)
        result = await apply_init_plan(plan, vault_root, agent_id, trace_id, config, profile)
        _record_init_event(
            "membank_init.apply_completed" if result.success else "membank_init.apply_failed",
            "INFO" if result.success else "ERROR",
            agent_id, trace_id, mode,
            message=result.message,
            config=config,
        )
        return result

    return MemBankInitResult(success=False, message=f"Unhandled mode: {mode}", trace_id=trace_id)
